name = "Cobblemon Neowo"
author = "HiiJax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f87982c6996999a0f8b95617c7376eac436bee03269e7e3e44e1eb129f39be8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.115"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/paxi/datapacks"
