name = "Cobblemon Neowo"
author = "HiiJax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce050038b320868ebd59bb7060029a42e3a871003346d315c5732033cb0d1a15"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.115"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/paxi/datapacks"
