name = "Cobblemon Neowo"
author = "HiiJax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3335a25d9041e2071871ac573404045f85d489e65c193a7b0c1cb5ce7b35ec93"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.115"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/paxi/datapacks"
