name = "Cobblemon Neowo"
author = "HiiJax"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbf51e551442b1695692e757b73bb55db75475918a21dfc1fc2c04e53e8722e6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/paxi/datapacks"
