name = "Cobblemon Neowo"
author = "HiiJax"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fb58033ea59dcefa0e64d3bf17ff2cde25c9d665e605875a51f713557069f50"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.115"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/paxi/datapacks"
