name = "Cobblemon Neowo"
author = "HiiJax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb946799a2e54b818a16041520e1d63f9d5e4af3da491f1a3dabf36cb86d9c7d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.115"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/paxi/datapacks"
