name = "Cobblemon Neowo"
author = "HiiJax"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12a495f2df3ade7c4690143d57c1f33448357ed4611a51709aaa556515962f82"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.115"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/paxi/datapacks"
